name: Node.js CI and Deployment

on:
  push:
    branches:
      - Main

jobs:
  build-and-deploy:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build


    - name: Deploy
      run: |
        # Add your deployment commands here
        # For example, deploy to a hosting service like Heroku, AWS, or Netlify
        # Replace this with the actual deployment commands you use
        echo "Deploying your application..."
        # Example: deploy to Heroku
        # heroku login -i
        # git push heroku Main
        echo "Deployment completed."

# Add more steps for deployment configuration as needed
